### ISSUE TITLE
Can't run the project on a server in eclipse

### ISSUE THREAD

**Issue by lseoo** [spring-guides/gs-securing-web#34]
I just cloned the project with "git clone https://github.com/spring-guides/gs-securing-web.git".
Then I opend the Project in Eclipse
![image](https://user-images.githubusercontent.com/29535476/38550418-c5e46da6-3cb6-11e8-8e9e-96f216799fcb.png)

After I wanted to start the completed version on my Tomcat v9.
![image](https://user-images.githubusercontent.com/29535476/38550453-e3dd8c5c-3cb6-11e8-820d-8641743c068a.png)

And then I'm getting this, no idea why.
![image](https://user-images.githubusercontent.com/29535476/38550371-9c516e94-3cb6-11e8-9393-7f0b74ac91ea.png)

I'm an absolut beginner, may this no issue rather a stupid question but this is the toutorial. In my eyes everything what just remontenly could be importend to run this project should stand in the doku.

Excuse my english, I'm from switzerland.

Thank you and Regards 
Leo

**Comment by gregturn** [comment]
What happens if you Run As > Spring Boot App?

**Comment by lseoo** [comment]
Works, thanks :)

**Comment by jzheaux** [comment]
Looks like this question has been answered, so I'll close the ticket. Feel free to reopen, though, if there is more to discuss.
