### ISSUE TITLE
This example doesn't work

### ISSUE THREAD

**Issue by er-han** [spring-guides/gs-securing-web#36]
I cloned the repository and run the 'complete' example app without any changes.
The app starts.
The problem is that I cannot log in.
I get `org.springframework.security.access.AccessDeniedException: Access is denied` exception when I try to log in with the user and password which are configured in the `UserDetailService`.
It is also an interesing fact that `ApplicationTests` runs successfully.
I wonder if this example is not up to date with `Spring Boot 2.0.+`

**Comment by shahinkl** [comment]
Please can you try clearing your browser cache and cookies once?

**Comment by er-han** [comment]
Yes, that worked. Thank you.

I have found why I get this problem
I have another application, which has OAuth2 for authentication, on localhost. It seems these two application's cookies mixed up. When I first log in to this form authentication application, the other one with Oauth2 authentication gets broken.

I know this is not anymore an issue with this repository, but this problem I just figured out led me think of a scenario which might come true for me soon. Can you tell me anything about this: 
I have an aplication that has Oauth2 for auth, let's say working on example.com. Now I need another application with form auth working on example.com:9090.  Will the cookies of both applications conflict?

**Comment by shahinkl** [comment]
Normally cookies are set at domain level. 
Please refer the below link to explore the possibility of custom cookies.

https://docs.spring.io/spring-session/docs/1.3.2.RELEASE/reference/html5/guides/custom-cookie.html

**Comment by er-han** [comment]
Thank you @shahinkl
