### ISSUE TITLE
user-defined 

### ISSUE THREAD

**Issue by OMGyang** [spring-guides/gs-securing-web#37]
When configuring the spring proxy as CGLIB
aop:
        proxy-target-class: true
employ user-defined   rememberMeService
![qq 20180809141531](https://user-images.githubusercontent.com/33895934/43881415-b626bd60-9bde-11e8-9cf9-3bd366e1ad5d.png)

**Comment by jzheaux** [comment]
@OMGyang if you are having trouble configuring Spring Security, beyond the steps indicated in the guide, I'd recommend you [post a question](https://stackoverflow.com/questions/ask) on StackOverflow, making sure to add the `spring-security` tag. 

If you believe you've identified an issue with Spring Security, you can [open a ticket](https://github.com/spring-projects/spring-security/issues/new) in the Spring Security github project.

As this ticket doesn't appear to be about the guide itself (it doesn't talk about how to define a custom remember me services), I'll close it. Feel free to reopen, though, if I've misunderstood.
