### ISSUE TITLE
redirect to a error page instead of previous requested page after login

### ISSUE THREAD

**Issue by hay-chan** [spring-guides/gs-securing-web#56]
Hi, I am trying to run the 'completed' demo in my local. 
I am expecting to go to the 'hello' page after login, but it redirect to a 'Error Page'. 
I tried SavedRequestAwareAuthenticationSuccessHandler, but it does not work, it still goes to the error page.

How should I do to land to the previous page after login?

**Comment by Buzzardo** [comment]
I can't re-create the problem.
