### ISSUE TITLE
Example Does not work: localhost:8080/login always returns Invalid username and password

### ISSUE THREAD

**Issue by michaelbedry** [spring-guides/gs-securing-web#63]
Example does not work.

localhost:8080/login always returns invalid username and password

If you are going to put something on Github you need to make sure the code works first.

**Comment by wild-o** [comment]
Attempted this exercise today as well. Same issue, it might have to do with the deprecated method.

**Comment by jfbueno** [comment]
Check if you're running the app in the **complete** folder.

**Comment by Buzzardo** [comment]
"If you are going to put something on Github you need to make sure the code works first."

It does work, and snark doesn't get you good replies.
