### ISSUE TITLE
withDefaultPasswordEncoder() is deprecated

### ISSUE THREAD

**Issue by SuleymanSchedules** [spring-guides/gs-securing-web#80]
The guide suggests the following: 
![image](https://github.com/user-attachments/assets/d91791e0-1bab-4a4b-88b9-7418db4b0ebb)

But the method is deprecated:
![image](https://github.com/user-attachments/assets/6645e647-04db-441d-bbd6-45b2b6d7d6e6)

**Comment by SuleymanSchedules** [comment]
Never mind, didn't see the 'but is acceptable for demos and getting started'. I still don't know how I feel about official guides teaching things that are only intended for samples

**Comment by ChristopherJTrent** [comment]
> I still don't know how I feel about official guides teaching things that are only intended for samples

I'm not convinced they actually want people using Spring. All of the guides they've put out explicitly do not teach acceptable production practices, and there is no documentation on how to complete these tasks correctly.
